# Site settings
title: James Hull
header-img: img/home-bg.jpg
email: bigfellahull@hotmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://jh.gs"
twitter_username: Bigfellahull
github_username:  Bigfellahull

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
