# Site settings
title: James Hull
header-img: img/home-bg.png
email: bigfellahull@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  James Hull on an assortment of topics.
baseurl: ""
url: "http://jh.gs"
twitter_username: Bigfellahull
github_username:  Bigfellahull

# Build settings
markdown: kramdown
highlighter: pygments
permalink: "/:title"
paginate: 5
exclude: ["less","README.md"]
